### ISSUE TITLE
Godot 4.0 version?

### ISSUE THREAD

**Issue by TheZoidMaster** [beeznutzdev/godot-click-through-transparent-window#2]
I was wanting to use this code for a Desktop Goose-like game, but when I went to use it, there were lots of errors, and I have no clue how to fix them.

**Comment by atadenizoktay** [comment]
The implementation that is done in this project does not support getting input from transparent areas, and I believe implementing most of the Desktop Goose's behavior is also not possible. Considering these, if you need a more flexible tool, you may like to use C# with certain libraries.

I certainly will make this project available in Godot 4 sometimes though, and I can speed up the process if it will help you with your project. Can you tell me more about the things you would like to achieve? @TheZoidMaster

**Comment by atadenizoktay** [comment]
I created two separate branches for Godot 3 and Godot 4. You can check the godot-4 branch to see if it's suitable for your work. Good luck! @TheZoidMaster
