### ISSUE TITLE
I know it's not an issue but I just wanna say thanks!

### ISSUE THREAD

**Issue by BeatMil** [beeznutzdev/godot-click-through-transparent-window#5]
I have been searching on how to make transparent background and click through for half a day now.
Thank you so much!
so sorry for making this fuss just to say thank you.

here is my cat XD
![lucky_cat](https://github.com/atadenizoktay/godot-click-through-transparent-window/assets/49752746/c34af7ae-24d8-4d44-b485-01c032c84e17)

**Comment by atadenizoktay** [comment]
That is an adorable cat! I'm glad the repository was of help; please let me know if you encounter any issues in the future. Have a good one!
